prompt compilando objeto SISTECSE.ALT_CCUST                                     
alter procedure SISTECSE.ALT_CCUST compile;                                     
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.LIMP_FORN_CGC                                 
alter procedure SISTECSE.LIMP_FORN_CGC compile;                                 
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.PR901                                         
alter procedure SISTECSE.PR901 compile;                                         
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.PR_ALTCC                                      
alter procedure SISTECSE.PR_ALTCC compile;                                      
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_BAIXA                                     
alter procedure SISTECSE.SCP_BAIXA compile;                                     
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_BANCO                                     
alter procedure SISTECSE.SCP_BANCO compile;                                     
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_CONHEC                                    
alter procedure SISTECSE.SCP_CONHEC compile;                                    
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_SEQMVCRE                                  
alter procedure SISTECSE.SCP_SEQMVCRE compile;                                  
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_SEQRAZAO                                  
alter procedure SISTECSE.SCP_SEQRAZAO compile;                                  
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_TRATA_CONTA                               
alter procedure SISTECSE.SCP_TRATA_CONTA compile;                               
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_TRATA_CREDITO                             
alter procedure SISTECSE.SCP_TRATA_CREDITO compile;                             
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_TRATA_FAT                                 
alter procedure SISTECSE.SCP_TRATA_FAT compile;                                 
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_TRATA_NOTA                                
alter procedure SISTECSE.SCP_TRATA_NOTA compile;                                
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_TRATA_OUTROS                              
alter procedure SISTECSE.SCP_TRATA_OUTROS compile;                              
show errors                                                                     
                                                                                
prompt compilando objeto SISTECSE.SCP_TRATA_TITULO                              
alter procedure SISTECSE.SCP_TRATA_TITULO compile;                              
show errors                                                                     
                                                                                
prompt compilando objeto IG2.IG2101SC                                           
alter procedure IG2.IG2101SC compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto IG2.IG2102SC                                           
alter procedure IG2.IG2102SC compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP1                                            
alter procedure CH_ADM.SCP1 compile;                                            
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP10                                           
alter procedure CH_ADM.SCP10 compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP12                                           
alter procedure CH_ADM.SCP12 compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP2                                            
alter procedure CH_ADM.SCP2 compile;                                            
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP3A                                           
alter procedure CH_ADM.SCP3A compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP3D                                           
alter procedure CH_ADM.SCP3D compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP3E                                           
alter procedure CH_ADM.SCP3E compile;                                           
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP4                                            
alter procedure CH_ADM.SCP4 compile;                                            
show errors                                                                     
                                                                                
prompt compilando objeto CH_ADM.SCP_SCPA05                                      
alter procedure CH_ADM.SCP_SCPA05 compile;                                      
show errors                                                                     
                                                                                
prompt compilando objeto CI_ADM.LIMP_FORN_CGC                                   
alter procedure CI_ADM.LIMP_FORN_CGC compile;                                   
show errors                                                                     
                                                                                
prompt compilando objeto CI_ADM.LIMP_FORN_CPF                                   
alter procedure CI_ADM.LIMP_FORN_CPF compile;                                   
show errors                                                                     
                                                                                
prompt compilando objeto CI_ADM.PR_DEL_PARCIAL                                  
alter procedure CI_ADM.PR_DEL_PARCIAL compile;                                  
show errors                                                                     
                                                                                

29 rows selected.

