
'PROMPTCOMPILANDOVIEW'||OWNER||'.'||OBJECT_NAME                                 
--------------------------------------------------------------------------------
'ALTERVIEW'||OWNER||'.'||OBJECT_NAME||'COMPILE;'                                
--------------------------------------------------------------------------------
Prompt Compilando View IG2.V_ALIQ_IMPOST_MERCDR_TEMP                            
alter view IG2.V_ALIQ_IMPOST_MERCDR_TEMP compile;                               
                                                                                
Prompt Compilando View IG2.V_CLASSF_FISCAL_TEMP                                 
alter view IG2.V_CLASSF_FISCAL_TEMP compile;                                    
                                                                                
Prompt Compilando View PO.FFV_01                                                
alter view PO.FFV_01 compile;                                                   
                                                                                

'PROMPTCOMPILANDOVIEW'||OWNER||'.'||OBJECT_NAME                                 
--------------------------------------------------------------------------------
'ALTERVIEW'||OWNER||'.'||OBJECT_NAME||'COMPILE;'                                
--------------------------------------------------------------------------------
Prompt Compilando View PO.FFV_02                                                
alter view PO.FFV_02 compile;                                                   
                                                                                
Prompt Compilando View OO.OM_SEGMENTS                                           
alter view OO.OM_SEGMENTS compile;                                              
                                                                                
Prompt Compilando View OO.OM_TABLESPACES                                        
alter view OO.OM_TABLESPACES compile;                                           
                                                                                

'PROMPTCOMPILANDOVIEW'||OWNER||'.'||OBJECT_NAME                                 
--------------------------------------------------------------------------------
'ALTERVIEW'||OWNER||'.'||OBJECT_NAME||'COMPILE;'                                
--------------------------------------------------------------------------------
Prompt Compilando View ICE.V_CNFRCA_AUDIT_EXTERN                                
alter view ICE.V_CNFRCA_AUDIT_EXTERN compile;                                   
                                                                                
Prompt Compilando View ICE.V_CONSUM_MAT                                         
alter view ICE.V_CONSUM_MAT compile;                                            
                                                                                
Prompt Compilando View ECO_IRM.ECO_DBA_WAITERS                                  
alter view ECO_IRM.ECO_DBA_WAITERS compile;                                     
                                                                                

9 linhas seleccionadas.

SQL> 
SQL> spool off
