-- Achar Pelo Telefone:
SELECT NUM_MEIO_ACESSO, NOME_CLIENTE, DATA_NASCIMENTO, NOME_FANTASIA, TIPO_LOGRADOURO_END_COBR, NOME_LOGRADOURO_END_COBR, NUM_PORTA_END_COBR, COMPLEMENTO_END_COBR, NOME_BAIRRO_END_COBR, NUM_CEP_END_COBR, NOME_LOCALIDADE_END_COBR, SIGLA_UF_END_COBR
FROM CLIENTE_FIXA.CLIENTE_FIXA
WHERE NUM_MEIO_ACESSO in
(
2126042598
);

-- Achar Cliente pelo Nome:
SELECT NUM_MEIO_ACESSO, NOME_CLIENTE, DATA_NASCIMENTO, NOME_FANTASIA, TIPO_LOGRADOURO_END_COBR, NOME_LOGRADOURO_END_COBR, NUM_PORTA_END_COBR, COMPLEMENTO_END_COBR, NOME_BAIRRO_END_COBR, NUM_CEP_END_COBR, NOME_LOCALIDADE_END_COBR, SIGLA_UF_END_COBR
FROM CLIENTE_FIXA.CLIENTE_FIXA
WHERE NOME_CLIENTE LIKE '%CLAUDIA%RODRIGUES%'
  -- AND NOME_BAIRRO_END_COBR='MARACANA'
  AND NOME_LOCALIDADE_END_COBR='RIO DE JANEIRO'
  AND SIGLA_UF_END_COBR='RJ'
/

-- Achar Pelo Endereço:
SELECT NUM_MEIO_ACESSO, NOME_CLIENTE, DATA_NASCIMENTO, NOME_FANTASIA, TIPO_LOGRADOURO_END_COBR, NOME_LOGRADOURO_END_COBR, NUM_PORTA_END_COBR, COMPLEMENTO_END_COBR, NOME_BAIRRO_END_COBR, NUM_CEP_END_COBR, NOME_LOCALIDADE_END_COBR, SIGLA_UF_END_COBR
FROM CLIENTE_FIXA.CLIENTE_FIXA
WHERE NOME_LOGRADOURO_END_COBR LIKE '%FRANCISCO%XAVIER%'
AND NOME_BAIRRO_END_COBR='MARACANA'
AND NUM_PORTA_END_COBR = '432'
AND COMPLEMENTO_END_COBR LIKE ''

-- Pelo CPF:
SELECT NUM_MEIO_ACESSO, NOME_CLIENTE, DATA_NASCIMENTO, NOME_FANTASIA, TIPO_LOGRADOURO_END_COBR, NOME_LOGRADOURO_END_COBR, NUM_PORTA_END_COBR, COMPLEMENTO_END_COBR, NOME_BAIRRO_END_COBR, NUM_CEP_END_COBR, NOME_LOCALIDADE_END_COBR, SIGLA_UF_END_COBR
FROM CLIENTE_FIXA.CLIENTE_FIXA
WHERE NUM_DOCUMENTO = '03649055732'
/
